server:
  port: 8888
  servlet:
    session:
      timeout: -1
#  error:
#    include-message: always
#    include-message: never

spring:
  application:
    name: KMS
  profiles:
    active: dev, prod
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/airline_db?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Europe/Moscow
    username: root
    password: root
    hikari:
      leak-detection-threshold: 60000
      maximum-pool-size: 20
  jpa:
    #show-sql: true
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        format_sql: true
        jdbc:
          time_zone: Europe/Moscow
  jackson:
    serialization:
      indent-output: true
# _method=PATCH -> POST
  mvc:
    hiddenmethod:
      filter:
        enabled: true
# thymeleaf
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix=: .html

springdoc:
  default-produces-media-type: application/json

kms:
  # Каталог хранения файлов с ключами и сертификатами. Выполняет роль хранилища,
  # отличного от хранилища других ключей и токенов (по PCI DSS).
  storeURI: "file:///C:/work/JavaProjects/GazpromBank/KMS/"
  key:
    ttl:
      # число лет до протухания ключа по умолчанию в зависимости от типа
      KEK: 10
      DEK: 5
  token:
    ttl:
      # число секунд хранения токена по умолчанию в зависимости от типа его основы
      PAN: 3600
